package com.example.utils

enum class Language(val code: String, val displayName: String, val flag: String) {
    ENGLISH("en", "English", "🇺🇸"),
    TURKISH("tr", "Türkçe", "🇹🇷"),
    SPANISH("es", "Español", "🇪🇸"),
    PORTUGUESE("pt", "Português (Brasil)", "🇧🇷"),
    HINDI("hi", "हिन्दी (Hindi)", "🇮🇳"),
    FRENCH("fr", "Français", "🇫🇷");

    companion object {
        fun fromCode(code: String): Language {
            return values().find { it.code.lowercase() == code.lowercase() } ?: ENGLISH
        }
        
        fun detectDeviceLanguage(): Language {
            val lang = java.util.Locale.getDefault().language
            return when (lang) {
                "tr" -> TURKISH
                "es" -> SPANISH
                "pt" -> PORTUGUESE
                "hi" -> HINDI
                "fr" -> FRENCH
                else -> ENGLISH
            }
        }
    }
}

object Localization {
    private val strings = mapOf(
        Language.ENGLISH to mapOf(
            "play_button" to "PLAY",
            "best_label" to "BEST",
            "sound_label" to "SOUND",
            "music_label" to "MUSIC",
            "on_label" to "ON",
            "off_label" to "OFF",
            "footer_text" to "EXTREME ARCADE • ONE TAP",
            "current_score" to "CURRENT SCORE",
            "tap_anywhere" to "TAP ANYWHERE TO TURN",
            "game_over" to "GAME OVER",
            "new_best" to "🔥 NEW BEST! 🔥",
            "score_label" to "SCORE",
            "best_score_label" to "BEST SCORE",
            "play_again" to "PLAY AGAIN",
            "main_menu" to "MAIN MENU",
            "language_label" to "LANGUAGE",
            "pts_label" to "PTS",
            "settings_title" to "SETTINGS",
            "music_volume_label" to "MUSIC VOLUME",
            "sfx_volume_label" to "SOUND EFFECTS",
            "close_button" to "CLOSE",
            "watch_ad_button" to "WATCH AD & CONTINUE",
            "pause_title" to "GAME PAUSED",
            "continue_button" to "CONTINUE",
            "restart_button" to "RESTART",
            "loading_ad" to "LOADING AD...",
            "vibration_label" to "VIBRATION",
            "intro_video_label" to "SPLASH SCREEN",
            "replay_intro_button" to "REPLAY SPLASH",
            "combo_tag" to "COMBO",
            "perfect_label" to "PERFECT!",
            "ad_preparing" to "Ad is preparing, please try again.",
            "skin_default" to "Default",
            "skin_neon" to "Neon Blue",
            "skin_lava" to "Lava Fire",
            "skin_ice" to "Ice Crystal",
            "skin_galaxy" to "Galaxy Space",
            "skin_gold" to "Golden Shine",
            "skin_emerald" to "Emerald Green",
            "skin_diamond" to "Diamond Ultra",
            "shop_title" to "SKIN SHOP",
            "buy_button" to "BUY",
            "select_button" to "SELECT",
            "selected_button" to "ACTIVE",
            "not_enough_coins" to "Not enough coins!",
            "coins_label" to "COINS",
            "perfect_run_bonus" to "PERFECT RUN BONUS!"
        ),
        Language.TURKISH to mapOf(
            "play_button" to "OYNA",
            "best_label" to "EN İYİ",
            "sound_label" to "SES",
            "music_label" to "MÜZİK",
            "on_label" to "AÇIK",
            "off_label" to "KAPALI",
            "footer_text" to "EKSTREM ARCAD • TEK TIK",
            "current_score" to "MEVCUT SKOR",
            "tap_anywhere" to "DÖNMEK İÇİN DOKUN",
            "game_over" to "OYUN BİTTİ",
            "new_best" to "🔥 YENİ REKOR! 🔥",
            "score_label" to "SKOR",
            "best_score_label" to "EN YÜKSEK SKOR",
            "play_again" to "TEKRAR OYNA",
            "main_menu" to "ANA MENÜ",
            "language_label" to "DİL",
            "pts_label" to "PUAN",
            "settings_title" to "AYARLAR",
            "music_volume_label" to "MÜZİK SESİ",
            "sfx_volume_label" to "SES EFEKTLERİ",
            "close_button" to "KAPAT",
            "watch_ad_button" to "REKLAM İZLE VE DEVAM ET",
            "pause_title" to "OYUN DURAKLATILDI",
            "continue_button" to "DEVAM ET",
            "restart_button" to "YENİDEN BAŞLAT",
            "loading_ad" to "REKLAM YÜKLENİYOR...",
            "vibration_label" to "TİTREŞİM",
            "intro_video_label" to "BAŞLANGIÇ EKRANI",
            "replay_intro_button" to "EKRANI TEKRARLA",
            "combo_tag" to "KOMBO",
            "perfect_label" to "HARİKA!",
            "ad_preparing" to "Reklam hazırlanıyor, lütfen tekrar deneyin.",
            "skin_default" to "Varsayılan",
            "skin_neon" to "Neon Mavi",
            "skin_lava" to "Lav Ateşi",
            "skin_ice" to "Buz Kristali",
            "skin_galaxy" to "Galaksi Uzayı",
            "skin_gold" to "Altın Parıltı",
            "skin_emerald" to "Zümrüt Yeşili",
            "skin_diamond" to "Elmas Ultra",
            "shop_title" to "SKİN MARKETİ",
            "buy_button" to "SATIN AL",
            "select_button" to "SEÇ",
            "selected_button" to "AKTİF",
            "not_enough_coins" to "Yetersiz coin!",
            "coins_label" to "COIN",
            "perfect_run_bonus" to "HATASIZ OYUN BONUSU!"
        ),
        Language.SPANISH to mapOf(
            "play_button" to "JUGAR",
            "best_label" to "RÉCORD",
            "sound_label" to "SONIDO",
            "music_label" to "MÚSICA",
            "on_label" to "SÍ",
            "off_label" to "NO",
            "footer_text" to "ARCADE EXTREMO • UN TOQUE",
            "current_score" to "PUNTAJE ACTUAL",
            "tap_anywhere" to "TOCA PARA GIRAR",
            "game_over" to "FIN DEL JUEGO",
            "new_best" to "🔥 ¡NUEVO RÉCORD! 🔥",
            "score_label" to "PUNTOS",
            "best_score_label" to "MEJOR PUNTUACIÓN",
            "play_again" to "VOLVER A JUGAR",
            "main_menu" to "MENÚ PRINCIPAL",
            "language_label" to "IDIOMA",
            "pts_label" to "PTS",
            "settings_title" to "AJUSTES",
            "music_volume_label" to "VOLUMEN DE MÚSICA",
            "sfx_volume_label" to "EFECTOS DE SONIDO",
            "close_button" to "CERRAR",
            "watch_ad_button" to "VER ANUNCIO Y CONTINUAR",
            "pause_title" to "JUEGO PAUSADO",
            "continue_button" to "CONTINUAR",
            "restart_button" to "REINICIAR",
            "loading_ad" to "CARGANDO ANUNCIO...",
            "vibration_label" to "VIBRACIÓN",
            "intro_video_label" to "PANTALLA DE INICIO",
            "replay_intro_button" to "REPETIR INICIO",
            "combo_tag" to "COMBO",
            "perfect_label" to "¡PERFECTO!",
            "ad_preparing" to "El anuncio se está preparando, por favor inténtalo de nuevo.",
            "skin_default" to "Predeterminado",
            "skin_neon" to "Azul Neón",
            "skin_lava" to "Fuego de Lava",
            "skin_ice" to "Cristal de Hielo",
            "skin_galaxy" to "Espacio Galáctico",
            "skin_gold" to "Brillo Dorado",
            "skin_emerald" to "Verde Esmeralda",
            "skin_diamond" to "Diamante Ultra",
            "shop_title" to "TIENDA DE ASPECTOS",
            "buy_button" to "COMPRAR",
            "select_button" to "SELECCIONAR",
            "selected_button" to "ACTIVO",
            "not_enough_coins" to "¡Monedas insuficientes!",
            "coins_label" to "MONEDAS",
            "perfect_run_bonus" to "¡BONO DE PARTIDA PERFECTA!"
        ),
        Language.PORTUGUESE to mapOf(
            "play_button" to "JOGAR",
            "best_label" to "RECORDE",
            "sound_label" to "SOM",
            "music_label" to "MÚSICA",
            "on_label" to "SIM",
            "off_label" to "NÃO",
            "footer_text" to "ARCADE EXTREMO • UM TOQUE",
            "current_score" to "PONTUAÇÃO",
            "tap_anywhere" to "TOQUE PARA VIRAR",
            "game_over" to "FIM DE JOGO",
            "new_best" to "🔥 NOVO RECORDE! 🔥",
            "score_label" to "PONTOS",
            "best_score_label" to "MELHOR PONTUAÇÃO",
            "play_again" to "JOGAR NOVAMENTE",
            "main_menu" to "MENU PRINCIPAL",
            "language_label" to "IDIOMA",
            "pts_label" to "PTS",
            "settings_title" to "CONFIGURAÇÕES",
            "music_volume_label" to "VOLUME DA MÚSICA",
            "sfx_volume_label" to "EFEITOS DE SOM",
            "close_button" to "FECHAR",
            "watch_ad_button" to "VER ANÚNCIO E CONTINUAR",
            "pause_title" to "JOGO PAUSADO",
            "continue_button" to "CONTINUAR",
            "restart_button" to "REINICIAR",
            "loading_ad" to "CARREGANDO ANÚNCIO...",
            "vibration_label" to "VIBRAÇÃO",
            "intro_video_label" to "TELA DE INÍCIO",
            "replay_intro_button" to "REPETIR INÍCIO",
            "combo_tag" to "COMBO",
            "perfect_label" to "PERFEITO!",
            "ad_preparing" to "O anúncio está sendo preparado, por favor tente novamente.",
            "skin_default" to "Padrão",
            "skin_neon" to "Neon Azul",
            "skin_lava" to "Fogo de Lava",
            "skin_ice" to "Cristal de Gelo",
            "skin_galaxy" to "Espaço Galáctico",
            "skin_gold" to "Brilho Dourado",
            "skin_emerald" to "Verde Esmeralda",
            "skin_diamond" to "Diamante Ultra",
            "shop_title" to "LOJA DE SKINS",
            "buy_button" to "COMPRAR",
            "select_button" to "SELECIONAR",
            "selected_button" to "ATIVO",
            "not_enough_coins" to "Moedas insuficientes!",
            "coins_label" to "MOEDAS",
            "perfect_run_bonus" to "BÔNUS DE PARTIDA PERFEITA!"
        ),
        Language.HINDI to mapOf(
            "play_button" to "खेलें",
            "best_label" to "सर्वश्रेष्ठ",
            "sound_label" to "आवाज़",
            "music_label" to "संगीत",
            "on_label" to "चालू",
            "off_label" to "बंद",
            "footer_text" to "रोमांचक आर्केड • एक टैप",
            "current_score" to "वर्तमान स्कोर",
            "tap_anywhere" to "मुड़ने के लिए कहीं भी टैप करें",
            "game_over" to "खेल खत्म",
            "new_best" to "🔥 नया रिकॉर्ड! 🔥",
            "score_label" to "स्कोर",
            "best_score_label" to "सर्वश्रेष्ठ स्कोर",
            "play_again" to "फिर से खेलें",
            "main_menu" to "मुख्य मेनू",
            "language_label" to "भाषा",
            "pts_label" to "अंक",
            "settings_title" to "सेटिंग्स",
            "music_volume_label" to "संगीत की आवाज़",
            "sfx_volume_label" to "ध्वни प्रभाव",
            "close_button" to "बंद करें",
            "watch_ad_button" to "विज्ञापन देखें और जारी रखें",
            "pause_title" to "खेल रुका हुआ है",
            "continue_button" to "जारी रखें",
            "restart_button" to "पुनः आरंभ करें",
            "loading_ad" to "विज्ञापन लोड हो रहा है...",
            "vibration_label" to "कंपन",
            "intro_video_label" to "स्प्लैश स्क्रीन",
            "replay_intro_button" to "स्प्लैश फिर देखें",
            "combo_tag" to "कॉम्बो",
            "perfect_label" to "उत्कृष्ट!",
            "ad_preparing" to "विज्ञापन तैयार हो रहा है, कृपया पुनः प्रयास करें।",
            "skin_default" to "डिफ़ॉल्ट",
            "skin_neon" to "नियॉन ब्लू",
            "skin_lava" to "लावा फायर",
            "skin_ice" to "बर्फ क्रिस्टल",
            "skin_galaxy" to "आकाशगंगा",
            "skin_gold" to "सुनहरी चमक",
            "skin_emerald" to "पन्ना हरा",
            "skin_diamond" to "अल्ट्रा हीरा",
            "shop_title" to "स्किन की दुकान",
            "buy_button" to "खरीदें",
            "select_button" to "चुनें",
            "selected_button" to "सक्रिय",
            "not_enough_coins" to "सिक्के पर्याप्त नहीं हैं!",
            "coins_label" to "सिक्के",
            "perfect_run_bonus" to "परफेक्ट रन बोनस!"
        ),
        Language.FRENCH to mapOf(
            "play_button" to "JOUER",
            "best_label" to "MEILLEUR",
            "sound_label" to "SON",
            "music_label" to "MUSIQUE",
            "on_label" to "OUI",
            "off_label" to "NON",
            "footer_text" to "ARCADE EXTRÊME • UN CLIC",
            "current_score" to "SCORE ACTUEL",
            "tap_anywhere" to "TAPOTEZ POUR TOURNER",
            "game_over" to "PARTIE TERMINÉE",
            "new_best" to "🔥 NOUVEAU RECORD ! 🔥",
            "score_label" to "SCORE",
            "best_score_label" to "MEILLEUR SCORE",
            "play_again" to "REJOUER",
            "main_menu" to "MENU PRINCIPAL",
            "language_label" to "LANGUE",
            "pts_label" to "PTS",
            "settings_title" to "PARAMÈTRES",
            "music_volume_label" to "VOLUME DE LA MUSIQUE",
            "sfx_volume_label" to "EFFETS SONORES",
            "close_button" to "FERMER",
            "watch_ad_button" to "REGARDER LA PUB & CONTINUER",
            "pause_title" to "JEU EN PAUSE",
            "continue_button" to "CONTINUER",
            "restart_button" to "RECOMMENCER",
            "loading_ad" to "CHARGEMENT DE LA PUB...",
            "vibration_label" to "VIBRATION",
            "intro_video_label" to "ÉCRAN DE DÉMARRAGE",
            "replay_intro_button" to "REJOUER L'ÉCRAN",
            "combo_tag" to "COMBO",
            "perfect_label" to "PARFAIT !",
            "ad_preparing" to "La publicité se prépare, veuillez réessayer.",
            "skin_default" to "Par défaut",
            "skin_neon" to "Bleu Néon",
            "skin_lava" to "Feu de Lave",
            "skin_ice" to "Cristal de Glace",
            "skin_galaxy" to "Espace Galactique",
            "skin_gold" to "Éclat Doré",
            "skin_emerald" to "Vert Émeraude",
            "skin_diamond" to "Diamant Ultra",
            "shop_title" to "BOUTIQUE DE SKINS",
            "buy_button" to "ACHETER",
            "select_button" to "SÉLECTIONNER",
            "selected_button" to "ACTIF",
            "not_enough_coins" to "Pièces insuffisantes !",
            "coins_label" to "PIÈCES",
            "perfect_run_bonus" to "BONUS RUN PARFAITE !"
        )
    )

    fun getString(language: Language, key: String): String {
        return strings[language]?.get(key) ?: strings[Language.ENGLISH]?.get(key) ?: key
    }
}
